// src/lib/worksData.js
export const WORKS = [
  {
    id: "w1",
    title: "Project Alpha",
    href: "/work/alpha",
    color: "#2563EB",
    logoText: "LOGO",          // atau logoSrc: "/logos/alpha.svg"
    year: "2024",
    tag: "UI/UX",
    bg: "/images/alpha.png",    // opsional, kalau kosong akan muncul placeholder
  },
  {
    id: "w2",
    title: "Project Beta",
    href: "/work/beta",
    color: "#F59E0B",
    logoText: "β",
    year: "2023",
    tag: "Web",
    bg: "/images/beta.png",
  },
  {
    id: "w3",
    title: "Project Gamma",
    href: "/work/gamma",
    color: "#10B981",
    logoText: "G",
    year: "2022",
    tag: "Brand",
    bg: "/images/gamma.png",
  },
  {
    id: "w4",
    title: "Project Delta",
    href: "/work/delta",
    color: "#EF4444",
    logoText: "Δ",
    year: "2021",
    tag: "3D",
    bg: "/images/delta.png",
  },
  {
    id: "w5",
    title: "Project Epsilon",
    href: "/work/epsilon",
    color: "#8B5CF6",
    logoText: "EPS",
    year: "2020",
    tag: "UI/UX",
    bg: "/images/epsilon.png",
  },
  {
    id: "w6",
    title: "Project Zeta",
    href: "/work/zeta",
    color: "#06B6D4",
    logoText: "ZETA",
    year: "2024",
    tag: "Motion",
    bg: "/images/zeta.png",
  },
  {
    id: "w7",
    title: "Project Eta",
    href: "/work/eta",
    color: "#F43F5E",
    logoText: "ETA",
    year: "2022",
    tag: "Web",
    bg: "/images/eta.png",
  },
  {
    id: "w8",
    title: "Project Theta",
    href: "/work/theta",
    color: "#22C55E",
    logoText: "TH",
    year: "2025",
    tag: "Product",
    bg: "/images/theta.png",
  },
];
