import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
import TransitionShell from "@/components/TransitionShell";

const jetbrains = JetBrains_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Your App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrains.className}>
        <TransitionShell>{children}</TransitionShell>
      </body>
    </html>
  );
}
